services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "38329:38329"
    command: sh -c "pnpm install && pnpm run dev"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
      - "8081:8081"
    depends_on:
      - frontend
    command: sh -c "npm install && node server.js"
